### ISSUE TITLE
Redmine 3.x compatibility ?

### ISSUE THREAD

**Issue by LeDistordu** [ixti/redmine_tags#104]
I have a problem with redmine 3.1 :

````
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `<<' for nil:NilClass
/var/redmine/plugins/redmine_tags/lib/redmine_tags/patches/issue_patch.rb:32:in `block in included'
/var/redmine/plugins/redmine_tags/lib/redmine_tags/patches/issue_patch.rb:27:in `class_eval'
/var/redmine/plugins/redmine_tags/lib/redmine_tags/patches/issue_patch.rb:27:in `included'
/var/redmine/plugins/redmine_tags/init.rb:46:in `include'
/var/redmine/plugins/redmine_tags/init.rb:46:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:192:in `call'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:180:in `each'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/var/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/railties-4.2.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
````

**Comment by mansandersson** [comment]
Having the same problem and found the following from the Redmine Forums. Seems to be a "common" issue.

http://www.redmine.org/issues/19230

**Comment by ilkosta** [comment]
+1

**Comment by PowerKiKi** [comment]
If one of you guys could create a PR about it, that would definitely increase the speed of resolution. Otherwise you may have to wait until someone else step up...

**Comment by KingBain** [comment]
@PowerKiKi a what ?

**Comment by PowerKiKi** [comment]
A [Pull Request](https://help.github.com/articles/using-pull-requests/) (or PR) is the GitHub way to send patches

**Comment by ali-sattari** [comment]
+1

**Comment by GremL1N** [comment]
+1

**Comment by Boldie** [comment]
The other tag plugin has the same problem:
https://github.com/Undev/redmine_tagging/issues/54

**Comment by Slind14** [comment]
:+1:

**Comment by EtherealLich** [comment]
I've made quick&dirty fix for Redmine 3.* compatibility. Not sure it will work, though :)

**Comment by PowerKiKi** [comment]
Thanks !

If a few users are able to test and confirm that it works it could be merged here

**Comment by cameyo42** [comment]
@EtherealLich trying your redmine_tags fix with redmine3.0.3 (from https://registry.hub.docker.com/u/sameersbn/redmine/) and a db upgraded from redmine2.6.2, I got 500 error:
* making a filter by tag
* creating a new tag

Making a filter by tag I got
```
Processing by IssuesController#index as HTML
  Parameters: {"fields"=>["tags", "status_id"], "operators"=>{"status_id"=>"o", "tags"=>"="}, "set_filter"=>"1", "values"=>{"status_id"=>[""], "tags"=>["cohesion"]}, "project_id"=>"attiweb-3"}
  Current user: c_giuliodori (id=3)
Completed 500 Internal Server Error in 255ms (ActiveRecord: 35.6ms)

ArgumentError (wrong number of arguments (1 for 2)):
  app/models/issue_query.rb:293:in `issue_count'
  app/controllers/issues_controller.rb:67:in `index'
```

Creating a new tag
```
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>"<E2><9C><93>", "authenticity_token"=>"...", "issue"=>{"is_private"=>"0", "project_id"=>"54", "tracker_id"=>"1", "subject"=>"test", "description"=>"test", "status_id"=>"1", "priority_id"=>"2", "assigned_to_id"=>"", "fixed_version_id"=>"", "parent_issue_id"=>"", "start_date"=>"2015-06-11", "due_date"=>"", "estimated_hours"=>"", "tag_list"=>"test", "notes"=>"", "private_notes"=>"0", "lock_version"=>"0"}, "was_default_status"=>"1", "last_journal_id"=>"", "commit"=>"Invia", "id"=>"132587"}
  Current user: c_giuliodori (id=3)
Completed 500 Internal Server Error in 93ms (ActiveRecord: 12.8ms)

RuntimeError (can't modify frozen ActiveSupport::HashWithIndifferentAccess):
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:162:in `call_hook'
  app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:180:in `update'
```

I hope this can help, sorry but I'm not a RoR dev.

**Comment by ilkosta** [comment]
@EtherealLich trying your redmine_tags fix with redmine3.0.3 (from https://registry.hub.docker.com/u/sameersbn/redmine/) and a db upgraded from redmine2.6.2, I got 500 error:
* making a filter by tag
* creating a new tag

Making a filter by tag I got
```
Processing by IssuesController#index as HTML
  Parameters: {"fields"=>["tags", "status_id"], "operators"=>{"status_id"=>"o", "tags"=>"="}, "set_filter"=>"1", "values"=>{"status_id"=>[""], "tags"=>["cohesion"]}, "project_id"=>"attiweb-3"}
  Current user: c_giuliodori (id=3)
Completed 500 Internal Server Error in 255ms (ActiveRecord: 35.6ms)

ArgumentError (wrong number of arguments (1 for 2)):
  app/models/issue_query.rb:293:in `issue_count'
  app/controllers/issues_controller.rb:67:in `index'
```

Creating a new tag
```
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>"<E2><9C><93>", "authenticity_token"=>"...", "issue"=>{"is_private"=>"0", "project_id"=>"54", "tracker_id"=>"1", "subject"=>"test", "description"=>"test", "status_id"=>"1", "priority_id"=>"2", "assigned_to_id"=>"", "fixed_version_id"=>"", "parent_issue_id"=>"", "start_date"=>"2015-06-11", "due_date"=>"", "estimated_hours"=>"", "tag_list"=>"test", "notes"=>"", "private_notes"=>"0", "lock_version"=>"0"}, "was_default_status"=>"1", "last_journal_id"=>"", "commit"=>"Invia", "id"=>"132587"}
  Current user: c_giuliodori (id=3)
Completed 500 Internal Server Error in 93ms (ActiveRecord: 12.8ms)

RuntimeError (can't modify frozen ActiveSupport::HashWithIndifferentAccess):
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:162:in `call_hook'
  app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:180:in `update'
```

I hope this can help, sorry but I'm not a RoR dev.

**Comment by EtherealLich** [comment]
Sorry, I forgot to say that I also made changes in gem acts-as-taggable-on-2.4.1
following this commit https://github.com/mbleigh/acts-as-taggable-on/pull/583/files
Patched file here
https://github.com/EtherealLich/acts-as-taggable-on/blob/patch-1/lib/acts_as_taggable_on/acts_as_taggable_on/core.rb

**Comment by ilkosta** [comment]
:clap: it worked!

**Comment by pka23** [comment]
Hi!
I've applied @EtherealLich 's patch from https://github.com/EtherealLich/redmine_tags/commit/ab27ee1cbb5ae179edb0a2ce989eb80eb21d3825 on redmine_tags plugin.
Then copied https://github.com/EtherealLich/acts-as-taggable-on/blob/patch-1/lib/acts_as_taggable_on/acts_as_taggable_on/core.rb  to /usr/local/lib/ruby/gems/2.0.0/gems/acts-as-taggable-on-2.4.1/lib/acts_as_taggable_on/acts_as_taggable_on/core.rb

Executed rake redmine:plugins:migrate RAILS_ENV=production
and migrating successfully complited
`[root@host redmine]# rake redmine:plugins:migrate RAILS_ENV=production`
`Migrating redmine_tags (redmine_tags)...`
`[root@host redmine]#`


Redmine Environment:
  Redmine version                3.0.1.stable
  Ruby version                   2.0.0-p247 (2013-06-27) [x86_64-linux]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               Mysql2

@LeDistordu Thank you!

**Comment by kusmierz** [comment]
+1

**Comment by dgm** [comment]
Is there a better way to work around the acts as taggable fix?

**Comment by dgm** [comment]
When I add multiple tags, and then edit the ticket, all the tags are now combined into one long tag

**Comment by dumblob** [comment]
+1

Redmine 3.x is with us already 5 months and many administrators are migrating to it. So I feel the need to acknowledge that this plugin is still **not** compatible with the 3.x Redmine.

**Comment by PowerKiKi** [comment]
@dumblob, submit a working PR that can be confirmed by a few users and it will get merged.

**Comment by janekska** [comment]
My setup:
Environment:
  Redmine version                3.0.3.stable
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.0.2
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  accept                         0.0.1
  event_notifications            3.0.0
  redmine_dashboard              2.5.0
  redmine_mail_reminder          3.0.0.0001
  redmine_spent_time_in_issue_description 2.7
  redmine_theme_changer          0.2.0
  redmine_timelog_timer          2.0.1
  redmine_work_time              0.3.1

Tried redmine tags from here:
https://github.com/ixti/redmine_tags/
getting error mentioned above:
rake aborted!
NoMethodError: undefined method `<<' for nil:NilClass

Then tried from here:
https://github.com/EtherealLich/redmine_tags
Rake was fine but when saving issue getting this error (also mentioned above):
RuntimeError (can't modify frozen ActiveSupport::HashWithIndifferentAccess)

If there is a new fix - I am ready to test it!

**Comment by glatapoui** [comment]
I confirm what @dgm mentioned a month ago: multiple tags become merged into a big one if you use the fix from @EtherealLich (https://github.com/EtherealLich/redmine_tags). I have tried to report that here with issue #110 (because I could not add it in the https://github.com/EtherealLich/redmine_tags) but it seems more related to the fix from @EtherealLich than the plugin from @ixti.

So @PowerKiKi, what information is needed in order to fix this issue ? How can I help ?

**Comment by PowerKiKi** [comment]
@glatapoui, like I said a few time in this thread, basicallly nobody has time to work on this project. So if you want something to be implemented, you will either have to submit a fully working PR or wait long enough until somebody else does.

That being said I personnally planned to migrate to Redmine in the forseeable future, so if nothing's done by then, I will do whatever it takes to solve compatibility issues... but don't hold your breath, it may still take weeks or even months...

**Comment by igroykt** [comment]
search does not work in EtherealLich/redmine_tags.

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'tags.name' in 'where clause': SELECT DISTINCT `issues`.`created_on`, `issues`.`id` FROM `issues` INNER JOIN `projects` ON `projects`.`id` = `issues`.`project_id` WHERE (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking')) AND (((subject LIKE '%sadsad%') OR (issues.description LIKE '%sadsad%') OR (tags.name LIKE '%sadsad%')))  ORDER BY `issues`.`created_on` DESC, `issues`.`id` DESC):
  lib/plugins/acts_as_searchable/lib/acts_as_searchable.rb:175:in `fetch_ranks_and_ids'
  lib/plugins/acts_as_searchable/lib/acts_as_searchable.rb:93:in `search_result_ranks_and_ids'
  lib/redmine/search.rb:127:in `block in load_result_ids'
  lib/redmine/search.rb:125:in `each'
  lib/redmine/search.rb:125:in `load_result_ids'
  lib/redmine/search.rb:115:in `block in load_result_ids_from_cache'
  lib/redmine/search.rb:114:in `load_result_ids_from_cache'
  lib/redmine/search.rb:99:in `result_ids'
  lib/redmine/search.rb:70:in `result_count'
  app/controllers/search_controller.rb:65:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

It can not find column name in table tags but column and table exists.

**Comment by gravis** [comment]
There are several forks out there which have fixed this issue. A PR will be hopefully soon created.

**Comment by igroykt** [comment]
@gravis thank! I found repo https://github.com/marius-balteanu/redmine_tags
and it works with:
>Environment:
  Redmine version                3.1.0.stable
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  redmine_apijs                  5.2.0
  redmine_checklists             3.1.1
  redmine_slack                  0.1
  redmine_tags                   2.0.1-dev

Now wiki and search working without error =)

**Comment by ixti** [comment]
If anyone wish to solve some merge conflicts and provide a PR with merge from https://github.com/marius-balteanu/redmine_tags -- will be happy to review and accept it.

**Comment by zzvv** [comment]
redmine-3.1.2-0/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.10.4/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /data in PATH, mode 040777
rake aborted!
NoMethodError: undefined method `<<' for nil:NilClass
/data/redmine/redmine-3.1.2-0/apps/redmine/htdocs/plugins/redmine_tags/lib/redmine_tags/patches/issue_patch.rb:33:in `block in included'
/data/redmine/redmine-3.1.2-0/apps/redmine/htdocs/plugins/redmine_tags/lib/redmine_tags/patches/issue_patch.rb:28:in `class_eval'
/data/redmine/redmine-3.1.2-0/apps/redmine/htdocs/plugins/redmine_tags/lib/redmine_tags/patches/issue_patch.rb:28:in `included'
/data/redmine/redmine-3.1.2-0/apps/redmine/htdocs/plugins/redmine_tags/init.rb:46:in `include'
/data/redmine/redmine-3.1.2-0/apps/redmine/htdocs/plugins/redmine_tags/init.rb:46:in `block in <top (required)>'
/data/redmine/redmine-3.1.2-0/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by igroykt** [comment]
@zzvv chmod 755 /data and check directory owner.

**Comment by hopewise** [comment]
Any news on a working version for Redmine 3.1 ?

**Comment by PowerKiKi** [comment]
@hopewise, not that I know of. It seems nobody took the time to build a fully working version (or at least never created a PR).

**Comment by marius-balteanu** [comment]
Hello,

We've merged the branch with redmine 3 compatibility into master. @hopewise, can you try the new version and confirm that works for you?

**Comment by janekska** [comment]
What about Redmine 3.0.3?
Could it work on 3.0.x too?

Bundle install went well, but RAILS_ENV=production rake redmine:plugins:migrate resulted in:
Redmine::PluginRequirementError: redmine_tags plugin requires Redmine 3.1.0 or higher but current is 3.0.3.stable

brgds
Janeks

**Comment by sdwolf** [comment]
@janekska I have not tested it on versions 3.0.x, so far only on 3.1.x and 3.2.0 but you could remove [this line] (https://github.com/ixti/redmine_tags/blob/master/init.rb#L32) and test it out.

**Comment by janekska** [comment]
Installs - o'k.
Configures - o'k

Added tags to existing issue results in error:
Started PATCH "/issues/419" for 159.148.51.12 at 2015-12-08 12:25:28 +0200
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Z4I9G...blabla...K+T0ZA+pJA3zXTpkttEKLakGb7iycQfzQ==", "issue"=>{"is_private"=>"0", "project_id"=>"4", "tracker_id"=>"3", "subject"=>"Our subject", "description"=>"", "status_id"=>"12", "priority_id"=>"2", "assigned_to_id"=>"4", "category_id"=>"35", "parent_issue_id"=>"", "start_date"=>"2015-12-07", "due_date"=>"2015-12-07", "estimated_hours"=>"0.5", "done_ratio"=>"0", "tag_list"=>"plānošana,datu apstrāde", "notes"=>"", "private_notes"=>"0", "lock_version"=>"1"}, "time_entry"=>{"hours"=>"", "activity_id"=>"", "comments"=>""}, "last_journal_id"=>"1782", "commit"=>"Nosūtīt", "id"=>"419"}
  Current user: janeks (id=3)
Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 1
Completed 500 Internal Server Error in 545ms (ActiveRecord: 78.4ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'taggings_count' in 'field list': UPDATE `tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `tags`.`id` = 1):
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:162:in `call_hook'
  app/controllers/issues_controller.rb:478:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:467:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:180:in `update'

**Comment by sdwolf** [comment]
Try the instructions from the ["To make it actually work"](https://github.com/ixti/redmine_tags#to-make-it-actually-work) section of the README.

Mainly you have to run `rake acts_as_taggable_on_engine:install:migrations` which will create a few migration files. Delete the first one and run `rake db:migrate`.

This is a workaround until I can figure out how to add them directly in @hdgarrood's [redmine_acts_as_taggable](https://github.com/hdgarrood/redmine_acts_as_taggable_on) gem.

**Comment by janekska** [comment]
I tried, but I am not sure if doing right. I did as written in "To make it actually work " and in Sdwolf description, but getting:

/usr/local/redmine# rake db:migrate
rake aborted!
ActiveRecord::AdapterNotSpecified: 'development' database is not configured. Available: ["production"]
...

**Comment by marius-balteanu** [comment]
please try with: `rake db:migrate RAILS_ENV=production`

**Comment by janekska** [comment]
Nice, it is working!
Only that I find that on new Wiki entry from, there was no tags field. But when editing - it is o'k.
My setup:
Environment:
  Redmine version                3.0.3.stable
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.0.2
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  accept                         0.0.1
  event_notifications            3.0.0
  redmine_contacts               4.0.2
  redmine_contacts_invoices      4.0.1
  redmine_dashboard              2.5.0
  redmine_logs                   0.1.0
  redmine_mail_reminder          3.0.0.0001
  redmine_spent_time_in_issue_description 2.7
  redmine_tags                   3.0.0
  redmine_theme_changer          0.2.0
  redmine_timelog_timer          2.0.1
  redmine_work_time              0.3.1

**Comment by hopewise** [comment]
@marius-balteanu I will test and tell you, thanks..

**Comment by marius-balteanu** [comment]
@janekska, please add another issue for the missing tag field on new Wiki entry forms in order to track it separately.

**Comment by hopewise** [comment]
I have cloned the repo and I've got this error when tried to bundle install:

```
/redmine_tags# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching git://github.com/sdwolf/redmine_acts_as_taggable_on.git
Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'acts-as-taggable-on (= 3.5) ruby' in any of the gem sources listed in your Gemfile or available on this machine.
root@redmine-jordan-test-tags:/srv/redmine/plugins/redmine_tags#
```

**Comment by sdwolf** [comment]
@hopewise you need to have git installed. `redmine_acts_as_taggable_on` gem is fetched from github since the upstream does not have rails 4 (redmine 3) compatibility. Also you might need to remove `Gemfile.lock` before running `bundle install` for this one instance.

**Comment by hopewise** [comment]
Thanks, I tried it, but unfortunately, I've got this error:

```
Message from application: redmine_tags plugin requires Redmine 3.1.0 or higher but current is 3.0.3.stable.14369 (Redmine::PluginRequirementError)
```

**Comment by sdwolf** [comment]
Remove [this line](https://github.com/ixti/redmine_tags/blob/master/init.rb#L32) and try again.
Note: when I will setup Travis I will also test against redmine 3.0.x, untill then the only ones for which I can say the plugin is compatible are 3.1.x and 3.2.0.

**Comment by hopewise** [comment]
Now I got error in the production.log file:

```
ActionView::Template::Error (undefined method `taggings_count' for #<ActsAsTaggableOn::Tag id: 47, name: "يزيد">):
    2:   <%= stylesheet_link_tag 'jquery.tagit.css', plugin: 'redmine_tags' %>
    3:   <%= stylesheet_link_tag 'redmine_tags', plugin: 'redmine_tags' %>
    4:   <h3><%= l :tags %></h3>
    5:   <%= render_sidebar_tags %>
    6: <% end %>
  lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in `map'
  lib/redmine/hook.rb:117:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
  app/views/issues/_sidebar.html.erb:18:in `_app_views_issues__sidebar_html_erb___1492490815478478557_70106597279280'
  app/views/issues/index.html.erb:99:in `block in _app_views_issues_index_html_erb__1555311557734628115_40272600'
  app/views/issues/index.html.erb:98:in `_app_views_issues_index_html_erb__1555311557734628115_40272600'
  app/controllers/issues_controller.rb:77:in `block (2 levels) in index'
  app/controllers/issues_controller.rb:76:in `index'
```

**Comment by sdwolf** [comment]
`rake db:migrate redmine:plugins:migrate RAILS_ENV=production`

**Comment by hopewise** [comment]
I already have migrated the old redmine_tags version, and there are already tags info in the DB
if I migrate DB again, I will lose tags info in data base?

**Comment by sdwolf** [comment]
No you will not lose any data if you migrate multiple times. It will continue from where you left off (last migration run)

**Comment by gravis** [comment]
Just installed the plugin from master.
Except the missing `taggings_count` column in my case (which was trivial to add), it's working! 
Thanks guys

**Comment by hopewise** [comment]
At last it worked!
But as for my case, my server was on production database, so I could not run migrate, I've added the missing field `taggings_count` directly on the table, and its working, thanks :+1:

**Comment by sdwolf** [comment]
@gravis @hopewise simply adding the column may solve the problem for now but the value of the column will not be initialized with the number of tagged elements and you will also miss all indexes added in the newer version of `acts-as-taggable-on`.

What I suggest is to wait for #114 to be merged, remove the `taggings_count` column you added and run `rake redmine:plugins:migrate RAILS_ENV=production` again.

**Comment by marius-balteanu** [comment]
merged #114

**Comment by hopewise** [comment]
That's the point, its a new server, I never run migrations, as my database
is already on the cloud..

**Comment by PowerKiKi** [comment]
Let's close this, because we now have Redmine 3 compatibility. If there are other issues to be discussed, open a new one.
